version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  dev:
    build: .
    image: shepherd:latest
    command: ./start.sh
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      RAILS_ENV: development
      GIT_USER: zeus-the-deployer
      GIT_ACCESS_TOKEN: a2a7ed05a57aebd33e15d2bf99c9da1927049c23
    # links:
      # - service1:service1
      # - service2:service2
      # - service3:service3
      # - service4:service4
      # - service5:service5
      # - service6:service6
      # - service7:service7
      # - service8:service8
      # - service9:service9
      # - service10:service10
      # - service11:service11
      # - service12:service12

  runner:
    image: eu.gcr.io/freska-production/system-test-runner
    environment:
      CATALOGUE_URL: "http://dev:4000"
      APP_NAME: test-app
    command: ["pwd"]
    depends_on:
      - dev

  # service1:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service2:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service3:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service4:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service5:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service6:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service7:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service8:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service9:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service10:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service11:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80

  # service12:
  #   build:
  #     context: ../sinatra_dummy_service
  #   ports:
  #     - 80
